### ISSUE TITLE
isGameOver()

### ISSUE THREAD

**Issue by sagemk** [dixoncs/PathOfTheDragon#7]
Determines if the game is over.

@return True, if the game is over.

**Comment by CamSmall** [comment]
isGameOver() will need to be called after the path hash map is updated. Because two ships may be effected by one tile they may both be thrown off the board at the same time (based on the end of the path they're on).

**Comment by sagemk** [comment]
-1 in the player position table for i, j, k in the GameState class will indicate that the Player is off the board and effectively out of the game

**Comment by sagemk** [comment]
field in GameState known as playerPositions[]. 2x3 int array. 
player 1 is row 0, player 2 is row 1. 
col 0 is tile i pos, col 1 is tile j pos, col 2 is point.

**Comment by sagemk** [comment]
`if (playerPositions[0][0] == -1 || playerPositions[1][0] == -1) {
return true;
}`

**Comment by dm0625** [comment]
Completed, pushed, and merged.

**Comment by sagemk** [comment]
Need to take in to account the first and second rounds when a player isn't technically on the board yet.

**Comment by sagemk** [comment]
Invalid now
